repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        pass_filenames: false
        additional_dependencies: ["ruff==0.8.6"]
      - id: ruff-lint
        name: ruff-lint
        entry: ruff check .
        language: python
        pass_filenames: false
        args: [--exit-zero]
        additional_dependencies: ["ruff==0.8.6"]
