repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: ruff
        language: system
        args: [check, --fix, --select, E,F]
      - id: ruff-format
        name: ruff-format
        entry: ruff
        language: system
        args: [format]
        pass_filenames: false
exclude: "^fluxmd/_ARCHIVE_simplified_version/|^docs/archive/|^legacy/|^preprint/"
