repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--exit-zero, --no-fix]
        types: [python]
        files: "^fluxmd/.*\\.py$"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        files: ^$
exclude: "^fluxmd/_ARCHIVE_simplified_version/|^docs/archive/|^legacy/"
