repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        pass_filenames: false
        additional_dependencies: ["ruff==0.8.6"]
      - id: ruff-lint
        name: ruff-lint
        entry: ruff check --exit-zero
        language: python
        pass_filenames: false
        additional_dependencies: ["ruff==0.8.6"]
exclude: '^docs/archive/|^legacy/'
