repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff
        language: python
        args: [format]
        additional_dependencies: ["ruff==0.8.6"]
        files: "\\.py$"
exclude: "^fluxmd/_ARCHIVE_simplified_version/|^docs/archive/|^legacy/"
