name: CI
on: { push: { branches: [main] }, pull_request: {} }

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Cache pip & pre-commit
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-${{ hashFiles('pyproject.toml','.pre-commit-config.yaml') }}

      - run: pip install --upgrade pip ruff pre-commit

      - name: Pre-commit (local hooks only)
        run: |
          pre-commit install
          pre-commit run --all-files

      - name: Install package
        run: pip install -e .

      - name: Unit tests
        run: pytest -q

      - name: Smoke run
        run: |
          mkdir -p tests/data
          touch tests/data/{protein.pdb,ligand.sdf}
          printf "mode: matryoshka\nprotein_file: protein.pdb\nligand_file: ligand.sdf\n" > tests/data/params.yaml
          python -m fluxmd.cli --protein tests/data/protein.pdb --ligand tests/data/ligand.sdf --params tests/data/params.yaml --dry-run
