name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  ACTIONS_STEP_DEBUG: false

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: git auth setup
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global --list | grep insteadOf
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dev deps
        run: pip install -e .[dev]
      - name: Run pre-commit (auth & verbose)
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRE_COMMIT_HOME: $HOME
        run: |
          set -euo pipefail
          set -x

          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global credential.helper "!f() { echo username=x-access-token; echo password=${TOKEN}; }; f"

          pre-commit install --hook-type pre-commit --hook-type commit-msg
          pre-commit run --all-files --show-diff-on-failure
      - run: black --check fluxmd/ tests/ --target-version py311
      - run: flake8 fluxmd/ tests/ --max-line-length=100
      - run: pytest --maxfail=1 --disable-warnings -q
