name: CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        run: PYTHONPATH=. pytest -q

  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install MkDocs
        run: |
          pip install "mkdocs-material>=9.1" || true
          pip install "mkdocs>=1.5" || pip install "mkdocs==1.*"
      - name: Build docs
        run: mkdocs build

  perf_regression:
    runs-on: ubuntu-latest
    continue-on-error: true
    environment: ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Allow outbound traffic to files.rcsb.org
        run: echo "NETWORK_ALLOWED_HOSTS=files.rcsb.org" >> $GITHUB_ENV
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run perf check
        run: |
          export CAP_NET=1
          PYTHONPATH=. pytest tests/perf_regression.py -q

  optional_CAP_bench:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run CAP benchmark
        run: PYTHONPATH=. python scripts/benchmark_CAP.py
